### ISSUE TITLE
errors when running the command $docker-compose pull --ignore-pull-failures

### ISSUE THREAD

**Issue by baekchun** [knowledge-discovery/hw2#5]
When I ran the command: $docker-compose pull --ignore-pull-failures

It gave me a bunch of errors saying that images were not found? 

Here's a list of errors I got when I ran that command: $docker-compose pull --ignore-pull-failures

ERROR: Error: image library/demographics-collater:latest not found
ERROR: Error: image library/model-trainer:latest not found
ERROR: Error: image library/model-classifier:latest not found
ERROR: Error: image library/feature-extractor:latest not found

And because of these errors, when I tried to build the dockerfiles with the command($docker-compose build --force-rm), no images were built

**Comment by TomLippincott** [comment]
Those are the images that you are supposed to build yourself: those pull errors are expected, hence the "--ignore-pull-failures" switch.
